INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Fundamental Programming Practices', 'CS390', null, 'L300', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Modern Programming Practices', 'CS401', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Database Systems', 'CS422', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Systems Analysis and Design', 'CS423', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Software Engineering', 'CS425', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Business Intelligence and Data Mining', 'CS430', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Algorithms', 'CS435', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Compiler Construction', 'CS440', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Computer Networks', 'CS450', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Software Testing', 'CS456', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Operating Systems', 'CS465', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Computer Security', 'CS466', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Secure Coding Practices', 'CS467', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Artificial Intelligence', 'CS470', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Parallel Programming', 'CS471', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Web Application Programming', 'CS472', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Mobile Device Programming', 'CS473', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Computer Graphics', 'CS475', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Image Processing', 'CS476', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Software Development with Fundamental Design Patterns', 'CS482', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Big Data Analytics', 'CS488', null, 'L400', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Science of Creative Intelligence', 'FOR500', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Advanced Computer Architecture', 'CS501', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Advanced Programming Languages', 'CS 505', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Big Data', 'CS522', null, 'L500', 1);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Big Data Technologies', 'CS523', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Advanced Software Development', 'CS525', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Enterprise Architecture', 'CS544', null, 'L500', 1);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Web Application Architecture and Frameworks', 'CS545', null, 'L500', 1);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Distributed Architecture', 'CS547', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Modern Web Applications', 'CS572', null, 'L500', 1);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Practicum in Software Development', 'CS575', null, 'L500', 0);
INSERT INTO cs425.course (name, code, `desc`, level, preNo) VALUES ('Machine Learning', 'CS582', null, 'L500', 0);